<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BatikSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $batiks = [
            //JAWA
            [
                'name' => "Batik Mega Mendung",
                'description' => "Batik Mega Mendung adalah salah satu motif batik yang ikonik dari Cirebon, Jawa Barat. Motifnya terinspirasi dari bentuk awan mendung dengan garis-garis yang melengkung dan warna-warna yang kontras, seperti biru, merah, dan ungu. Filosofi dari Batik Mega Mendung adalah tentang ketenangan, kesabaran, dan pengendalian diri dalam menghadapi berbagai situasi hidup. Seperti awan yang tenang sebelum datangnya hujan, manusia diharapkan bisa bersikap tenang dalam menghadapi emosi dan cobaan hidup. Selain itu, motif Mega Mendung juga mencerminkan akulturasi budaya antara masyarakat Cirebon dan budaya Tiongkok, yang masuk melalui perdagangan pada masa lalu. Awan melambangkan kebebasan dan harapan, sedangkan warna-warna cerah menunjukkan keceriaan dan semangat hidup. Dengan filosofi yang kaya ini, Batik Mega Mendung menjadi simbol penting dalam budaya dan sejarah masyarakat Cirebon, serta salah satu warisan budaya Indonesia yang diakui dunia.",
                'city' => "Cirebon",
                'provinceId' => 12,
                'islandId' => 1,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Jawa/MegaMendung.png?t=2024-10-14T08%3A25%3A03.717Z",
            ],
            [
                'name' => "Batik Pekalongan",
                'description' => "Batik Pekalongan dikenal dengan motif-motif yang kaya akan warna dan lebih bebas dalam bentuknya, dibandingkan dengan batik dari daerah lain di Jawa. Batik ini sering kali menampilkan motif flora, fauna, dan kehidupan sehari-hari yang dipengaruhi oleh budaya Tiongkok, Eropa, Arab, dan Melayu. Batik Pekalongan adalah contoh dari kemampuan masyarakat untuk beradaptasi dengan pengaruh luar tanpa meninggalkan identitas lokal. Filosofinya adalah keterbukaan terhadap perubahan dan keberagaman, namun tetap berpegang pada akar tradisional. Keterampilan tangan yang diturunkan dari generasi ke generasi juga menjadi simbol penting dari penghargaan terhadap tradisi.",
                'city' => "Pekalongan",
                'provinceId' => 14,
                'islandId' => 1,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Jawa/Pekalongan.webp?t=2024-10-14T07%3A54%3A55.019Z",
            ],
            [
                'name' => "Batik Sogan",
                'description' => "Batik Sogan merupakan batik tradisional yang berasal dari Yogyakarta dan Surakarta. Batik ini biasanya berwarna coklat dengan pola-pola klasik seperti motif parang, kawung, dan lainnya. Warna coklat sogan yang khas menciptakan kesan elegan dan mewah. Filosofi dari Batik Sogan adalah tentang kebijaksanaan, ketenangan, serta penghormatan terhadap nilai-nilai luhur dalam kehidupan. Pola dan motifnya sering dikaitkan dengan simbol kebangsawanan, karena dahulu batik jenis ini hanya dikenakan oleh kalangan keraton. Saat ini, Batik Sogan tidak hanya menjadi kebanggaan masyarakat Jawa, namun juga menjadi salah satu simbol budaya Indonesia yang dikenal hingga mancanegara.",
                'city' => "Yogyakarta",
                'provinceId' => 15,
                'islandId' => 1,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Jawa/Sogan.jpg?t=2024-10-14T08%3A24%3A36.097Z",
            ],
            [
                'name' => "Batik Gentongan",
                'description' => "Batik Gentongan berasal dari Madura dan dikenal dengan proses pembuatannya yang unik menggunakan gentong atau tong sebagai tempat merendam kain dalam pewarnaan. Motif Batik Gentongan biasanya mencerminkan kehidupan sehari-hari masyarakat Madura, seperti flora, fauna, dan simbol-simbol tradisional lainnya. Warna-warna cerah seperti merah, biru, dan hijau mendominasi batik ini, memberikan kesan ceria dan penuh semangat. Filosofi dari Batik Gentongan adalah tentang ketekunan dan kesabaran dalam menjalani kehidupan, mencerminkan proses pembuatannya yang membutuhkan waktu lama dan ketelitian tinggi. Batik ini juga menunjukkan hubungan harmonis antara manusia dan alam yang telah menjadi bagian dari budaya Madura sejak lama.",
                'city' => "Bangkalan",
                'provinceId' => 16,
                'islandId' => 1,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Jawa/Gentongan.jpeg?t=2024-10-14T08%3A24%3A18.842Z",
            ],
            [
                'name' => "Batik Kraton",
                'description' => "Batik Kraton adalah salah satu batik klasik yang berasal dari lingkungan keraton di Yogyakarta dan Surakarta. Motif-motifnya sangat kaya akan makna filosofis dan simbol-simbol yang berkaitan dengan kebijaksanaan, keberanian, dan kesucian. Dulu, batik ini hanya dikenakan oleh kalangan keraton atau bangsawan sebagai simbol status sosial. Motif-motif seperti parang, kawung, dan meru merupakan yang paling terkenal dari Batik Kraton. Filosofi dari Batik Kraton menekankan pentingnya keselarasan antara manusia dengan alam dan nilai-nilai spiritual. Setiap motif yang dihasilkan memiliki makna mendalam, seperti harapan akan kehidupan yang seimbang, harmoni, serta ketentraman batin. Batik ini menjadi warisan budaya yang sangat dihargai dan dilestarikan hingga sekarang.",
                'city' => "Yogyakarta",
                'provinceId' => 15,
                'islandId' => 1,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Jawa/Kraton.png?t=2024-10-14T08%3A24%3A03.927Z",
            ],
            [
                'name' => "Batik Simbut",
                'description' => "Batik Simbut berasal dari suku Baduy di Banten dan memiliki motif yang sederhana namun penuh makna. Motif Simbut menggambarkan bentuk dedaunan atau sulur-suluran yang mencerminkan kesederhanaan hidup masyarakat Baduy yang menyatu dengan alam. Batik ini dibuat dengan pewarna alami, menggunakan teknik yang diwariskan dari generasi ke generasi. Filosofi dari Batik Simbut adalah tentang kesederhanaan, ketulusan, serta kebersamaan dengan alam. Masyarakat Baduy percaya bahwa hidup yang selaras dengan alam akan membawa kedamaian dan kesejahteraan. Batik Simbut menjadi simbol kekayaan budaya yang menjaga kearifan lokal dan identitas komunitas adat Baduy.",
                'city' => "Lebak",
                'provinceId' => 13,
                'islandId' => 1,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Jawa/Simbut.jpeg?t=2024-10-14T08%3A23%3A41.210Z",
            ],
            [
                'name' => "Batik Parang",
                'description' => "Batik Parang merupakan salah satu motif batik tertua di Indonesia, dengan motif menyerupai ombak yang berulang dan diagonal. Asal-usulnya dari Keraton Yogyakarta dan Surakarta, dan motif ini menggambarkan semangat yang tidak pernah padam, kekuatan, serta perjuangan yang terus-menerus. Filosofinya adalah semangat pantang menyerah dalam menghadapi kehidupan, seperti ombak yang terus bergulir tanpa henti. Batik Parang juga melambangkan hubungan yang erat antara manusia dengan Sang Pencipta. Dulu, motif ini hanya boleh dipakai oleh keluarga kerajaan sebagai simbol kebijaksanaan dan kekuatan. Kini, Batik Parang menjadi salah satu simbol kebanggaan budaya Indonesia yang dikenal luas.",
                'city' => "Surakarta",
                'provinceId' => 14,
                'islandId' => 1,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Jawa/Parang.jpeg?t=2024-10-14T08%3A23%3A32.148Z",
            ],
            [
                'name' => "Batik Kawung",
                'description' => "Batik Kawung adalah motif batik yang terkenal dari Yogyakarta dan Jawa Tengah, dengan pola geometris yang menyerupai irisan buah kawung atau kolang-kaling. Motif ini dikenal dengan keteraturannya yang mencerminkan nilai-nilai kesederhanaan, kejujuran, serta keikhlasan. Batik Kawung sering dikaitkan dengan makna spiritualitas dan kebijaksanaan, yang menggambarkan kesucian dan kemurnian hati. Dulu, motif Kawung sering digunakan oleh raja atau pejabat tinggi sebagai simbol kebangsawanan dan keagungan. Filosofi dari Batik Kawung mengajarkan tentang keseimbangan antara dunia fisik dan spiritual, serta harapan untuk hidup yang sejahtera dan harmonis. Batik ini tetap menjadi salah satu motif yang digemari karena keindahan dan makna yang terkandung di dalamnya.",
                'city' => "Yogyakarta",
                'provinceId' => 15,
                'islandId' => 1,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Jawa/Kawung.jpg?t=2024-10-14T08%3A23%3A01.443Z",
            ],
            [
                'name' => "Batik Geblek Renteng",
                'description' => "Batik Geblek Renteng adalah batik khas dari Kulon Progo, DI Yogyakarta. Motifnya terinspirasi dari makanan tradisional setempat yang disebut geblek, yakni sejenis camilan berbahan dasar singkong. Motif ini memiliki pola berbentuk lingkaran yang saling terhubung, menyerupai bentuk geblek yang berjejer. Filosofi dari Batik Geblek Renteng adalah tentang kebersamaan, gotong royong, dan kekompakan dalam masyarakat. Motif ini juga menggambarkan nilai-nilai tradisional yang masih dijaga oleh masyarakat Kulon Progo, serta semangat untuk melestarikan budaya lokal. Warna-warna batik ini umumnya lembut dan natural, mencerminkan kesederhanaan serta kehangatan dari kehidupan masyarakat Kulon Progo.",
                'city' => "Kulon Progo",
                'provinceId' => 15,
                'islandId' => 1,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Jawa/Geblek%20Renteng.jpg?t=2024-10-14T08%3A22%3A47.556Z",
            ],

            //SUMATRA
            [
                'name' => "Batik Tanah Liek",
                'description' => "Batik Tanah Liek adalah batik khas dari Sumatera Barat yang menggunakan tanah liat sebagai bahan pewarna alami. Proses pembuatannya yang unik ini menciptakan warna coklat kemerahan yang khas dan alami. Batik ini sering kali menampilkan motif-motif khas Minangkabau, seperti rumah gadang, motif flora, serta ukiran tradisional. Filosofi Batik Tanah Liek mencerminkan hubungan erat antara manusia dan alam, serta keberanian untuk mempertahankan tradisi di tengah modernisasi. Motifnya sering kali mengandung makna kehidupan masyarakat Minang yang penuh kearifan lokal, serta nilai-nilai adat yang dijunjung tinggi, seperti kebersamaan dan gotong royong. Batik ini adalah simbol kekayaan budaya Sumatera Barat yang terus dilestarikan oleh masyarakat setempat.",
                'city' => "Padang",
                'provinceId' => 3,
                'islandId' => 2,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Sumatra/Batik%20Tanah%20Liek.jpg?t=2024-10-14T14%3A12%3A30.015Z",
            ],
            [
                'name' => "Batik Kapal Sanggat",
                'description' => "Batik Kapal Sanggat berasal dari Kalimantan Barat, dengan motif utama berupa kapal yang melambangkan peran penting sungai dan laut dalam kehidupan masyarakat pesisir Kalimantan. Motif ini menggambarkan perjalanan hidup yang penuh tantangan, namun tetap berlayar dengan semangat yang tinggi. Warna-warna yang digunakan biasanya gelap dengan kombinasi warna merah dan hitam, memberikan kesan yang kuat dan berani. Filosofi Batik Kapal Sanggat mengajarkan tentang keteguhan dalam menghadapi arus kehidupan dan pentingnya menjalin hubungan baik dengan alam. Batik ini menjadi salah satu warisan budaya yang menggambarkan identitas masyarakat pesisir Kalimantan Barat dan mencerminkan semangat mereka dalam menghadapi tantangan hidup di sepanjang perairan sungai dan laut.",
                'city' => "Pontianak",
                'provinceId' => 6,
                'islandId' => 2,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Sumatra/Kapal%20Sanggat.jpg?t=2024-10-14T14%3A12%3A39.588Z",
            ],
            [
                'name' => "Batik Keluak Daun Pakis",
                'description' => "Batik Keluak Daun Pakis merupakan batik khas dari Papua yang mengambil inspirasi dari flora khas Papua, yaitu daun pakis. Motif ini menggambarkan daun pakis yang tumbuh subur di alam Papua, dengan sentuhan warna alami yang didapat dari bahan pewarna tradisional seperti keluak. Batik ini mencerminkan harmoni antara masyarakat Papua dan alam sekitarnya, serta nilai-nilai tradisi yang diwariskan secara turun temurun. Filosofinya adalah tentang kehidupan yang tumbuh dan berkembang dalam lingkungan yang penuh tantangan namun tetap mempertahankan keaslian. Batik Keluak Daun Pakis juga mencerminkan rasa syukur masyarakat Papua terhadap alam yang memberikan banyak sumber kehidupan. Motif ini menjadi simbol kebanggaan dan identitas lokal yang unik.",
                'city' => "Jayapura",
                'provinceId' => 3,
                'islandId' => 2,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Sumatra/Keluak%20Daun%20Pakis.jpeg?t=2024-10-14T14%3A12%3A49.577Z",
            ],
            [
                'name' => "Batik Rangkiang",
                'description' => "Batik Rangkiang adalah batik khas dari Sumatera Barat yang terinspirasi dari rangkiang, yaitu lumbung padi tradisional Minangkabau. Motif ini melambangkan kemakmuran, kesuburan, dan kerja keras masyarakat dalam mengolah hasil bumi. Batik ini sering kali menampilkan bentuk geometris yang menyerupai rangkiang dengan pola-pola yang rapi dan simetris. Filosofi Batik Rangkiang adalah tentang pentingnya menyimpan hasil bumi sebagai persiapan untuk masa depan, serta kebersamaan dalam bekerja untuk kesejahteraan bersama. Warna-warna batik ini cenderung hangat dengan dominasi warna coklat, merah, dan hitam yang menunjukkan karakter kuat masyarakat Minangkabau. Batik Rangkiang menjadi salah satu simbol budaya yang mencerminkan identitas lokal Sumatera Barat yang kaya.",
                'city' => "Bukittinggi",
                'provinceId' => 3,
                'islandId' => 2,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Sumatra/Rangkiang.jpeg?t=2024-10-14T14%3A12%3A57.191Z",
            ],
            [
                'name' => "Batik Pucuak Rabuang",
                'description' => "Batik Pucuak Rabuang berasal dari Sumatera Barat, dengan motif utama berupa pucuak rabuang atau pucuk rebung. Motif ini menggambarkan pertumbuhan dan harapan, di mana pucuk rebung melambangkan regenerasi dan kelanjutan kehidupan. Batik ini mengajarkan tentang pentingnya menjaga nilai-nilai tradisi sambil tetap terbuka terhadap perkembangan zaman. Filosofinya adalah semangat untuk terus tumbuh dan berkembang seperti pucuk rebung yang selalu menuju ke atas. Batik Pucuak Rabuang sering kali menggunakan warna-warna natural yang mencerminkan alam Sumatera Barat, seperti hijau, coklat, dan merah. Batik ini adalah salah satu simbol budaya Minangkabau yang kaya akan nilai-nilai filosofis dan estetika.",
                'city' => "Padang",
                'provinceId' => 3,
                'islandId' => 2,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Sumatra/Pucuak%20Rabuang.png?t=2024-10-14T14%3A13%3A10.940Z",
            ],
            [
                'name' => "Batik Cual",
                'description' => "Batik Cual adalah batik tradisional dari Bangka Belitung yang memiliki keunikan dalam penggunaan benang emas dan motif-motif yang rumit. Batik ini sering kali menampilkan pola-pola yang terinspirasi dari alam laut dan kehidupan masyarakat pesisir, seperti motif ikan, bunga, dan ombak. Penggunaan benang emas memberikan kesan mewah dan elegan pada batik ini, menjadikannya simbol status dan kemewahan pada zaman dahulu. Filosofi dari Batik Cual adalah tentang keberanian dalam mengejar keindahan dan keagungan, serta apresiasi terhadap kekayaan alam laut yang menjadi bagian penting dari kehidupan masyarakat Bangka Belitung. Batik ini kini menjadi salah satu produk unggulan yang mengangkat budaya lokal ke kancah nasional.",
                'city' => "Pangkal Pinang",
                'provinceId' => 8,
                'islandId' => 2,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Sumatra/Cual.jpg?t=2024-10-14T14%3A13%3A30.044Z",
            ],

            //Kalimantan
            [
                'name' => "Batik Bayam Raja",
                'description' => "Batik Bayam Raja adalah batik khas dari Kalimantan Selatan yang terkenal dengan motif bayam raja yang menggambarkan tumbuhan bayam sebagai simbol kekuatan dan kesuburan. Motif ini melambangkan keseimbangan alam dan kehidupan yang selaras dengan hutan Kalimantan yang luas. Batik ini mengajarkan filosofi tentang kelestarian alam dan pentingnya menjaga keseimbangan antara manusia dan lingkungan. Warna-warna yang digunakan sering kali mencerminkan warna alami dari hutan Kalimantan, seperti hijau dan cokelat, memberikan kesan yang natural dan elegan. Batik Bayam Raja sering dipakai dalam berbagai upacara adat dan acara formal sebagai bentuk penghormatan terhadap tradisi leluhur yang kuat.",
                'city' => "Banjarmasin",
                'provinceId' => 22,
                'islandId' => 3,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Kalimantan/bayam%20raja.webp",
            ],
            [
                'name' => "Batik Tampuk Manggis",
                'description' => "Batik Tampuk Manggis merupakan batik dari Kalimantan Barat yang terinspirasi dari bentuk buah manggis yang melambangkan kekayaan dan kemakmuran. Motif tampuk manggis di batik ini sering kali disajikan dalam pola simetris yang indah, mencerminkan keindahan alam Kalimantan Barat. Filosofi dari Batik Tampuk Manggis adalah tentang kesabaran dan ketekunan dalam menjalani kehidupan, seperti halnya proses menanam dan merawat manggis. Batik ini sering digunakan dalam upacara adat dan perayaan budaya sebagai simbol kesuburan dan kesejahteraan masyarakat Kalimantan Barat.",
                'city' => "Pontianak",
                'provinceId' => 20,
                'islandId' => 3,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Kalimantan/Tampuk%20Manggis.jpg?t=2024-10-14T14%3A34%3A09.251Z",
            ],
            [
                'name' => "Batik Kangkung Kaombakan",
                'description' => "Batik Kangkung Kaombakan adalah batik khas Kalimantan Tengah yang menampilkan motif tanaman kangkung yang bergelombang, menggambarkan kehidupan masyarakat pesisir dan aliran sungai yang menjadi sumber kehidupan di Kalimantan. Filosofi dari Batik Kangkung Kaombakan adalah tentang fleksibilitas dan kemampuan beradaptasi dengan perubahan, seperti aliran air sungai yang terus mengalir. Warna-warna yang digunakan cenderung mencerminkan alam seperti hijau, biru, dan cokelat, yang memberikan nuansa alami dan segar. Batik ini sering digunakan sebagai pakaian dalam acara-acara adat, melambangkan keterikatan dengan alam dan kehidupan yang harmonis.",
                'city' => "Palangka Raya",
                'provinceId' => 21,
                'islandId' => 3,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Kalimantan/KangkungKaorakan.png?t=2024-10-14T14%3A34%3A15.441Z",
            ],
            [
                'name' => "Batik Benang Bintik",
                'description' => "Batik Benang Bintik adalah batik dari Kalimantan Tengah yang terinspirasi dari motif benang dengan pola titik-titik kecil yang membentuk gambar alam dan kehidupan masyarakat Dayak. Batik ini mencerminkan keragaman budaya dan kekayaan tradisi suku Dayak, yang sangat menghargai alam dan lingkungan. Filosofi dari Batik Benang Bintik adalah tentang ketelitian dan keindahan dalam kesederhanaan, serta pentingnya menjaga harmoni antara manusia dan alam. Warna-warna yang digunakan sering kali memiliki nuansa tanah dan hutan, menggambarkan kedekatan dengan alam Kalimantan.",
                'city' => "Palangka Raya",
                'provinceId' => 21,
                'islandId' => 3,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Kalimantan/BenakBintik.jpg?t=2024-10-14T14%3A34%3A22.828Z",
            ],
            [
                'name' => "Batik Awan Berarak",
                'description' => "Batik Awan Berarak adalah batik tradisional dari Kalimantan Timur yang memiliki motif awan yang bergerak, melambangkan kebebasan dan harapan. Motif ini terinspirasi dari bentuk awan yang berubah-ubah dan selalu bergerak, mencerminkan semangat masyarakat Kalimantan Timur dalam menghadapi perubahan. Filosofi dari Batik Awan Berarak adalah tentang fleksibilitas dan optimisme, serta pentingnya menjaga kebersamaan dalam menghadapi tantangan. Batik ini sering dipakai dalam acara adat dan sebagai simbol dari semangat kebebasan dan keterbukaan.",
                'city' => "Samarinda",
                'provinceId' => 23,
                'islandId' => 3,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Kalimantan/AwanBerarak.jpg?t=2024-10-14T14%3A34%3A31.411Z",
            ],
            [
                'name' => "Batik Tidayu",
                'description' => "Batik Tidayu adalah batik khas dari Kalimantan Barat yang menggabungkan unsur-unsur dari tiga etnis utama, yaitu Tionghoa, Dayak, dan Melayu. Motif batik ini menampilkan perpaduan antara pola-pola geometris, flora, dan simbol-simbol etnis yang mencerminkan kebersamaan dan keragaman budaya. Filosofi dari Batik Tidayu adalah tentang toleransi dan kebersamaan dalam keberagaman, serta pentingnya menghargai setiap warisan budaya yang ada. Batik ini sering dipakai dalam acara kebudayaan untuk mempererat persaudaraan antar etnis di Kalimantan Barat.",
                'city' => "Pontianak",
                'provinceId' => 20,
                'islandId' => 3,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Kalimantan/Tidayu.jpeg?t=2024-10-14T14%3A34%3A38.603Z",
            ],
            [
                'name' => "Batik Batang Garing",
                'description' => "Batik Batang Garing berasal dari Kalimantan Tengah dan merupakan simbol dari kehidupan suku Dayak Ngaju. Motif Batang Garing ini menggambarkan pohon kehidupan yang melambangkan kekuatan spiritual dan keterikatan dengan alam. Batik ini sering digunakan dalam ritual adat dan upacara penting suku Dayak sebagai simbol penghormatan kepada leluhur. Filosofi dari Batik Batang Garing adalah tentang keseimbangan antara alam, manusia, dan roh-roh nenek moyang. Warna-warna yang digunakan sering kali cerah dan berani, seperti merah, kuning, dan hijau, menggambarkan semangat yang hidup dan dinamis.",
                'city' => "Palangka Raya",
                'provinceId' => 21,
                'islandId' => 3,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Kalimantan/BatangGaring.jpg?t=2024-10-14T14%3A34%3A45.697Z",
            ],
            [
                'name' => "Batik Tarakan",
                'description' => "Batik Tarakan adalah batik dari Kalimantan Utara yang memiliki motif yang menggambarkan kehidupan pesisir dan kekayaan laut. Motif ini sering kali menampilkan bentuk-bentuk ikan, ombak, dan kapal, yang mencerminkan hubungan erat masyarakat Tarakan dengan laut sebagai sumber mata pencaharian. Filosofi dari Batik Tarakan adalah tentang kebersamaan dan kerja keras dalam menjaga kelestarian laut. Batik ini mencerminkan identitas masyarakat pesisir yang kuat dan tradisi maritim yang telah ada sejak lama. Warna-warna yang digunakan mencerminkan laut seperti biru dan hijau, memberikan kesan segar dan alami.",
                'city' => "Tarakan",
                'provinceId' => 24,
                'islandId' => 3,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Kalimantan/Tarakan.jpg?t=2024-10-14T14%3A34%3A53.929Z",
            ],
            [
                'name' => "Batik Sasirangan",
                'description' => "Batik Sasirangan adalah batik tradisional dari Kalimantan Selatan yang awalnya digunakan sebagai kain upacara penyembuhan suku Banjar. Motif-motif pada Batik Sasirangan memiliki makna simbolis yang kuat, seperti kekuatan, keberanian, dan keteguhan. Batik ini memiliki pola yang dibuat dengan cara mencelupkan kain yang telah diikat dengan benang, sehingga menciptakan pola unik yang berbeda-beda. Filosofi dari Batik Sasirangan adalah tentang semangat hidup dan ketahanan menghadapi berbagai cobaan. Batik ini telah menjadi identitas budaya suku Banjar dan populer sebagai pakaian dalam berbagai acara adat.",
                'city' => "Banjarmasin",
                'provinceId' => 22,
                'islandId' => 3,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Kalimantan/Sasirangan.jpg",
            ],
            [
                'name' => "Batik Dayak Kamang",
                'description' => "Batik Dayak Kamang berasal dari Kalimantan Barat dan dikenal dengan motif-motif yang terinspirasi dari seni ukir Dayak. Motifnya sering kali berupa simbol-simbol mistis, flora, dan fauna yang melambangkan kekuatan spiritual dan keterikatan dengan alam. Filosofi dari Batik Dayak Kamang adalah tentang menjaga warisan budaya dan kearifan lokal suku Dayak yang telah diwariskan secara turun temurun. Batik ini mengajarkan pentingnya melestarikan tradisi dan hidup selaras dengan alam. Warna-warna yang digunakan biasanya mencerminkan warna alami, seperti cokelat, hijau, dan merah.",
                'city' => "Pontianak",
                'provinceId' => 20,
                'islandId' => 3,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Kalimantan/Dayak%20Kamang.jpeg",
            ],

            //Sulawesi
            [
                'name' => "Batik Tari Kabasaran",
                'description' => "Batik Tari Kabasaran adalah batik khas Sulawesi Utara yang terinspirasi dari tari perang tradisional Kabasaran, yang merupakan tarian adat masyarakat Minahasa. Motif batik ini menampilkan elemen-elemen seperti pakaian dan senjata yang digunakan dalam tarian tersebut, menggambarkan semangat keberanian dan kepahlawanan. Filosofi dari Batik Tari Kabasaran adalah tentang keberanian dan semangat juang dalam mempertahankan kehormatan dan tradisi. Batik ini sering dipakai dalam acara adat dan perayaan budaya sebagai simbol penghormatan terhadap para leluhur yang berani.",
                'city' => "Manado",
                'provinceId' => 29,
                'islandId' => 4,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Sulawesi/Kabasaran.png?t=2024-10-14T14%3A50%3A52.046Z",
            ],
            [
                'name' => "Batik Karawo",
                'description' => "Batik Karawo berasal dari Gorontalo di Sulawesi, dikenal karena teknik pembuatannya yang unik dengan cara memotong kain secara manual untuk menciptakan pola-pola yang halus dan rumit. Batik ini sering menampilkan motif-motif alam seperti bunga, tumbuhan, dan pola geometris. Filosofi dari Batik Karawo adalah tentang ketekunan, kesabaran, dan keindahan dalam detail. Batik Karawo banyak digunakan dalam berbagai acara adat dan upacara resmi, serta menjadi kebanggaan masyarakat Gorontalo sebagai salah satu warisan budaya yang bernilai tinggi.",
                'city' => "Gorontalo",
                'provinceId' => 31,
                'islandId' => 4,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Sulawesi/Karawo.jpeg",
            ],
            [
                'name' => "Batik Bomba",
                'description' => "Batik Bomba adalah batik khas dari Sulawesi Tengah yang memiliki motif-motif terinspirasi dari budaya dan alam setempat. 'Bomba' sendiri dalam bahasa setempat berarti motif atau corak. Batik ini sering menampilkan pola-pola seperti flora, fauna, dan motif khas suku Kaili. Filosofi dari Batik Bomba adalah tentang keindahan alam Sulawesi Tengah dan pentingnya melestarikan budaya lokal. Batik ini digunakan dalam berbagai upacara adat dan kegiatan budaya sebagai bentuk penghargaan terhadap tradisi dan alam.",
                'city' => "Palu",
                'provinceId' => 30,
                'islandId' => 4,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Sulawesi/Bomba.jpg",
            ],
            [
                'name' => "Batik Wakatobi",
                'description' => "Batik Wakatobi berasal dari Sulawesi Tenggara dan terinspirasi dari keindahan laut dan terumbu karang yang ada di kepulauan Wakatobi, yang merupakan salah satu kawasan wisata bahari terbaik di Indonesia. Motif batik ini sering menampilkan bentuk-bentuk biota laut seperti ikan, karang, dan ombak, mencerminkan kekayaan laut yang dimiliki oleh Sulawesi Tenggara. Filosofi dari Batik Wakatobi adalah tentang kelestarian alam laut dan hubungan erat masyarakat dengan laut sebagai sumber kehidupan. Batik ini sering digunakan dalam acara-acara resmi dan kebudayaan untuk memperkenalkan kekayaan alam daerah Wakatobi.",
                'city' => "Wakatobi",
                'provinceId' => 33,
                'islandId' => 4,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Sulawesi/Wakatobi.png?t=2024-10-14T14%3A51%3A21.619Z",
            ],
            [
                'name' => "Batik La Galigo",
                'description' => "Batik La Galigo adalah batik dari Sulawesi Selatan yang terinspirasi dari epos kuno 'La Galigo', yang menceritakan kisah kehidupan masyarakat Bugis di masa lampau. Motif-motif pada Batik La Galigo sering menggambarkan simbol-simbol budaya dan kehidupan masyarakat Bugis seperti perahu, padi, dan rumah adat. Filosofi dari Batik La Galigo adalah tentang kebijaksanaan dan nilai-nilai luhur yang diajarkan dalam cerita tersebut. Batik ini digunakan dalam berbagai upacara adat dan kegiatan budaya untuk melestarikan warisan sastra dan budaya Bugis.",
                'city' => "Makassar",
                'provinceId' => 32,
                'islandId' => 4,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Sulawesi/La%20Galigo.jpeg?t=2024-10-14T14%3A51%3A27.657Z",
            ],
            [
                'name' => "Batik Jagung",
                'description' => "Batik Jagung merupakan batik dari Sulawesi Selatan yang terinspirasi dari tanaman jagung, yang menjadi salah satu komoditas penting di wilayah tersebut. Motif batik ini menggambarkan bentuk jagung dan daunnya, sebagai simbol kemakmuran dan keberkahan bagi masyarakat. Filosofi dari Batik Jagung adalah tentang ketekunan dalam bercocok tanam dan pentingnya menjaga kelestarian lingkungan untuk keberlangsungan hidup. Batik ini sering digunakan dalam acara panen raya atau kegiatan kebudayaan yang terkait dengan pertanian.",
                'city' => "Gowa",
                'provinceId' => 32,
                'islandId' => 4,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Sulawesi/Jagung.png",
            ],
            [
                'name' => "Batik Toraja",
                'description' => "Batik Toraja berasal dari Sulawesi Selatan dan memiliki motif-motif yang terinspirasi dari ukiran tradisional masyarakat Toraja. Motif batik ini sering menampilkan pola-pola geometris dan bentuk-bentuk simbolis yang mencerminkan kehidupan spiritual masyarakat Toraja, seperti motif rumah Tongkonan dan motif kerbau. Filosofi dari Batik Toraja adalah tentang kehidupan setelah mati, keberanian, dan hubungan antara manusia dan leluhur. Batik ini sering digunakan dalam upacara adat Toraja sebagai bentuk penghormatan kepada para leluhur.",
                'city' => "Rantepao",
                'provinceId' => 32,
                'islandId' => 4,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Sulawesi/Toraja.jpg?t=2024-10-14T14%3A51%3A46.627Z",
            ],
            [
                'name' => "Batik Paqbarre Allo",
                'description' => "Batik Paqbarre Allo adalah batik khas Sulawesi Selatan yang terinspirasi dari alam dan kebudayaan Bugis-Makassar. Nama 'Paqbarre Allo' berarti bayangan atau cahaya matahari dalam bahasa setempat, sehingga motif-motif pada batik ini sering kali menampilkan bentuk-bentuk sinar matahari dan simbol-simbol alam lainnya. Filosofi dari Batik Paqbarre Allo adalah tentang kehangatan, optimisme, dan semangat hidup. Batik ini sering digunakan dalam kegiatan kebudayaan sebagai simbol dari harapan dan semangat yang tinggi.",
                'city' => "Makassar",
                'provinceId' => 32,
                'islandId' => 4,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Sulawesi/Paqbarreallo.webp?t=2024-10-14T14%3A51%3A58.790Z",
            ],
            [
                'name' => "Batik Taiganja",
                'description' => "Batik Taiganja merupakan batik dari Sulawesi Barat yang memiliki motif-motif yang terinspirasi dari budaya Mandar, suku asli Sulawesi Barat. Motif batik ini sering menggambarkan kehidupan masyarakat pesisir dan motif-motif alam seperti perahu dan laut, yang mencerminkan ketergantungan masyarakat Mandar pada hasil laut. Filosofi dari Batik Taiganja adalah tentang ketangguhan dalam menghadapi ombak kehidupan dan pentingnya menjaga tradisi maritim. Batik ini digunakan dalam acara-acara adat sebagai simbol dari identitas masyarakat Mandar.",
                'city' => "Mamuju",
                'provinceId' => 34,
                'islandId' => 4,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Sulawesi/Taiganja.jpg?t=2024-10-14T14%3A52%3A08.999Z",
            ],
            [
                'name' => "Batik Tongkonan",
                'description' => "Batik Tongkonan adalah batik dari Sulawesi Selatan yang terinspirasi dari rumah adat Tongkonan milik masyarakat Toraja. Motif-motif pada batik ini sering menggambarkan bentuk-bentuk atap dan ukiran khas rumah Tongkonan, yang melambangkan kekuatan, perlindungan, dan kehangatan keluarga. Filosofi dari Batik Tongkonan adalah tentang ikatan keluarga dan pentingnya menjaga nilai-nilai tradisi dalam kehidupan sehari-hari. Batik ini banyak digunakan dalam upacara adat Toraja sebagai bentuk penghormatan terhadap leluhur dan simbol dari persatuan keluarga.",
                'city' => "Rantepao",
                'provinceId' => 32,
                'islandId' => 4,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Sulawesi/Tongkonan.jpeg?t=2024-10-14T14%3A52%3A15.734Z",
            ],

            //Papua
            [
                'name' => "Batik Cendrawasih",
                'description' => "Batik Cendrawasih merupakan batik khas Papua yang terinspirasi dari burung Cendrawasih, yang dikenal sebagai 'burung surga'. Motif batik ini sering menampilkan gambar burung Cendrawasih dengan warna-warna cerah dan corak yang dinamis, menggambarkan keindahan alam Papua. Filosofi dari Batik Cendrawasih adalah tentang keindahan dan kebebasan, serta simbol kebanggaan terhadap kekayaan alam Papua. Batik ini banyak digunakan dalam acara adat dan perayaan budaya sebagai wujud penghargaan terhadap keanekaragaman hayati Papua.",
                'city' => "Jayapura",
                'provinceId' => 35,
                'islandId' => 5,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Papua/Cendrawasih.jpeg?t=2024-10-14T15%3A10%3A13.096Z",
            ],
            [
                'name' => "Batik Kamoro",
                'description' => "Batik Kamoro berasal dari suku Kamoro di Papua dan memiliki motif-motif yang menggambarkan kehidupan masyarakat suku Kamoro, seperti ukiran kayu, perahu, dan aktivitas sehari-hari. Batik ini sering menampilkan pola-pola geometris yang mencerminkan keahlian seni ukir masyarakat Kamoro. Filosofi dari Batik Kamoro adalah tentang hubungan erat antara manusia dan alam, serta pentingnya menjaga kelestarian budaya leluhur. Batik ini digunakan dalam berbagai upacara adat sebagai simbol identitas dan warisan budaya suku Kamoro.",
                'city' => "Timika",
                'provinceId' => 35,
                'islandId' => 5,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Papua/Kamoro.jpg?t=2024-10-14T15%3A10%3A25.419Z",
            ],
            [
                'name' => "Batik Prada",
                'description' => "Batik Prada adalah batik khas Papua yang terkenal dengan hiasan emas atau perak yang memberikan kesan mewah dan elegan. Motif-motif batik ini sering kali terinspirasi dari budaya lokal, seperti ukiran tradisional dan simbol-simbol kepercayaan masyarakat Papua. Filosofi dari Batik Prada adalah tentang kemuliaan dan kemegahan, serta penghormatan terhadap tradisi dan adat istiadat. Batik ini sering digunakan dalam acara resmi dan upacara adat sebagai simbol kebanggaan dan status sosial.",
                'city' => "Jayapura",
                'provinceId' => 35,
                'islandId' => 5,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Papua/Prada.jpeg?t=2024-10-14T15%3A10%3A31.826Z",
            ],
            [
                'name' => "Batik Asmat",
                'description' => "Batik Asmat berasal dari suku Asmat di Papua dan dikenal dengan motif-motif yang terinspirasi dari ukiran kayu khas suku Asmat. Motif batik ini sering menggambarkan kehidupan masyarakat Asmat, termasuk perahu, patung leluhur, dan simbol-simbol alam. Filosofi dari Batik Asmat adalah tentang penghormatan terhadap leluhur dan pentingnya menjaga keseimbangan dengan alam. Batik ini digunakan dalam upacara adat suku Asmat sebagai bagian dari tradisi yang diwariskan dari generasi ke generasi.",
                'city' => "Agats",
                'provinceId' => 35,
                'islandId' => 5,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Papua/AsmatPapua.jpeg?t=2024-10-14T15%3A10%3A41.504Z",
            ],
            [
                'name' => "Batik Tifa Honai",
                'description' => "Batik Tifa Honai merupakan batik yang menggambarkan alat musik tradisional Papua, yaitu Tifa, serta rumah adat Honai. Motif batik ini sering menggambarkan bentuk Tifa yang melambangkan semangat dan kebersamaan masyarakat Papua. Filosofi dari Batik Tifa Honai adalah tentang kekuatan, kebersamaan, dan kearifan lokal yang menjadi ciri khas masyarakat Papua. Batik ini sering digunakan dalam acara-acara adat dan perayaan budaya sebagai simbol identitas dan kebanggaan terhadap tradisi Papua.",
                'city' => "Jayapura",
                'provinceId' => 35,
                'islandId' => 5,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Papua/Tifa%20Honai.jpg?t=2024-10-14T15%3A10%3A47.812Z",
            ],
            [
                'name' => "Batik Sentani",
                'description' => "Batik Sentani berasal dari daerah Sentani di Papua dan memiliki motif-motif yang terinspirasi dari kehidupan masyarakat di sekitar Danau Sentani. Motif-motif batik ini sering menggambarkan ikan, perahu, dan ombak, mencerminkan kehidupan masyarakat yang bergantung pada danau sebagai sumber penghidupan. Filosofi dari Batik Sentani adalah tentang kelestarian alam dan pentingnya menjaga hubungan harmonis dengan lingkungan. Batik ini digunakan dalam berbagai upacara adat sebagai bentuk penghormatan terhadap alam dan budaya setempat.",
                'city' => "Sentani",
                'provinceId' => 35,
                'islandId' => 5,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Papua/Sentani.jpeg?t=2024-10-14T15%3A10%3A55.938Z",
            ],
            [
                'name' => "Batik Tifa",
                'description' => "Batik Tifa adalah batik khas Papua yang menampilkan motif alat musik tradisional Tifa, yang digunakan dalam berbagai upacara adat dan kegiatan kebudayaan masyarakat Papua. Motif Tifa pada batik ini melambangkan kekuatan dan kebersamaan, serta pentingnya peran musik dalam kehidupan sosial masyarakat Papua. Filosofi dari Batik Tifa adalah tentang keharmonisan dan semangat gotong royong dalam menjaga tradisi dan adat istiadat. Batik ini sering digunakan dalam acara adat sebagai bentuk penghargaan terhadap musik dan seni tradisional Papua.",
                'city' => "Jayapura",
                'provinceId' => 35,
                'islandId' => 5,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Papua/Tifa.png?t=2024-10-14T15%3A11%3A01.519Z",
            ],
            [
                'name' => "Batik Kamaro Timika",
                'description' => "Batik Kamaro Timika berasal dari daerah Timika di Papua, dengan motif yang terinspirasi dari kebudayaan lokal dan kehidupan masyarakat di sekitar wilayah tersebut. Batik ini sering menampilkan pola-pola geometris yang melambangkan keseimbangan alam dan kehidupan sehari-hari. Filosofi dari Batik Kamaro Timika adalah tentang keindahan kehidupan sederhana dan harmonisasi antara manusia dan alam. Batik ini digunakan dalam berbagai acara adat dan perayaan budaya sebagai bentuk penghormatan terhadap tradisi lokal.",
                'city' => "Timika",
                'provinceId' => 35,
                'islandId' => 5,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Papua/Kamaro%20Timika.png?t=2024-10-14T15%3A10%3A19.053Z",
            ],
            [
                'name' => "Batik Raja Ampat",
                'description' => "Batik Raja Ampat berasal dari wilayah kepulauan Raja Ampat di Papua Barat dan dikenal dengan motif-motif yang terinspirasi dari keindahan alam bawah laut dan keragaman hayati laut di wilayah tersebut. Motif batik ini sering menggambarkan ikan, terumbu karang, dan kehidupan laut lainnya, yang menjadi daya tarik wisata utama di Raja Ampat. Filosofi dari Batik Raja Ampat adalah tentang kelestarian lingkungan laut dan pentingnya menjaga kekayaan alam untuk generasi mendatang. Batik ini digunakan dalam berbagai acara kebudayaan untuk memperkenalkan keindahan alam Papua Barat.",
                'city' => "Waisai",
                'provinceId' => 36,
                'islandId' => 5,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Papua/RajaAmpat.png?t=2024-10-14T15%3A11%3A16.160Z",
            ],
            [
                'name' => "Batik Ukir Sentani",
                'description' => "Batik Ukir Sentani adalah batik khas Papua yang terinspirasi dari seni ukir tradisional masyarakat Sentani. Motif batik ini sering menggambarkan pola-pola ukiran yang mencerminkan kekayaan budaya dan kearifan lokal masyarakat sekitar Danau Sentani. Filosofi dari Batik Ukir Sentani adalah tentang penghormatan terhadap tradisi dan seni yang diwariskan dari generasi ke generasi. Batik ini digunakan dalam berbagai upacara adat dan acara kebudayaan sebagai simbol identitas dan kebanggaan masyarakat Sentani, serta sebagai wujud cinta terhadap budaya dan alam di sekitar mereka.",
                'city' => "Sentani",
                'provinceId' => 35,
                'islandId' => 5,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Papua/Ukir%20Sentani.jpg?t=2024-10-14T15%3A11%3A22.610Z",
            ],

            //Maluku
            [
                'name' => "Batik Alam Pantai",
                'description' => "Batik Alam Pantai terinspirasi dari keindahan pantai-pantai di Maluku yang menampilkan keanekaragaman hayati laut. Motifnya menggambarkan ombak, pasir, dan berbagai kehidupan laut yang menjadi bagian dari budaya dan kehidupan masyarakat pesisir. Batik ini mencerminkan hubungan harmonis antara manusia dan alam serta mengajak pemakainya untuk menjaga kelestarian lingkungan. Dengan warna-warna cerah yang mencerminkan kehidupan di laut, batik ini sering digunakan dalam acara tradisional dan perayaan sebagai simbol kebanggaan akan kekayaan alam Maluku.",
                'city' => "Ambon",
                'provinceId' => 31,
                'islandId' => 6,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Maluku/Alam%20Pantai.png?t=2024-10-14T15%3A24%3A57.163Z",
            ],
            [
                'name' => "Batik Burung Bidadari",
                'description' => "Batik Burung Bidadari menggambarkan keindahan burung-burung eksotis yang ada di Maluku. Motif ini melambangkan keberanian dan keanggunan, mencerminkan filosofi kehidupan masyarakat yang selaras dengan alam. Burung-burung ini juga menjadi simbol kebebasan dan harapan, menjadikan batik ini pilihan yang populer dalam berbagai acara formal dan informal. Dengan detail yang rumit dan warna yang cerah, batik ini menunjukkan keterampilan tangan yang tinggi dari pengrajin Maluku.",
                'city' => "Ambon",
                'provinceId' => 31,
                'islandId' => 6,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Maluku/BurungBidadari.jpeg?t=2024-10-14T15%3A25%3A49.049Z",
            ],
            [
                'name' => "Batik Cakalele",
                'description' => "Batik Cakalele terinspirasi dari tarian tradisional Cakalele yang terkenal di Maluku. Motif batik ini sering menampilkan gerakan dan keanggunan tarian, melambangkan kekuatan dan semangat juang masyarakat Maluku. Dengan warna-warna yang cerah dan dinamis, batik ini sering digunakan dalam acara-acara budaya dan festival untuk menunjukkan identitas budaya yang kaya. Cakalele menjadi simbol persatuan dan kebanggaan akan warisan budaya yang harus dilestarikan.",
                'city' => "Ambon",
                'provinceId' => 31,
                'islandId' => 6,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Maluku/Cakalele.jpeg?t=2024-10-14T15%3A25%3A55.932Z",
            ],
            [
                'name' => "Batik Tubo Kelapa",
                'description' => "Batik Tubo Kelapa menggambarkan pohon kelapa yang menjadi simbol kehidupan masyarakat Maluku. Motif batik ini menunjukkan berbagai bagian dari pohon kelapa dan penggunaannya dalam kehidupan sehari-hari, dari makanan hingga kerajinan tangan. Filosofi di balik batik ini adalah tentang ketahanan dan keberlanjutan, mencerminkan bagaimana masyarakat Maluku memanfaatkan sumber daya alam dengan bijak. Batik ini sangat cocok untuk digunakan dalam berbagai kesempatan, memperlihatkan kecintaan akan alam dan budaya lokal.",
                'city' => "Ambon",
                'provinceId' => 31,
                'islandId' => 6,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Maluku/Tubo%20Kelapa.jpg?t=2024-10-14T15%3A26%3A02.794Z",
            ],
            [
                'name' => "Batik Pattimura",
                'description' => "Batik Pattimura menghormati pahlawan nasional, Thomas Matulessy, atau lebih dikenal sebagai Patimura, yang berjuang melawan penjajahan di Maluku. Motif batik ini melambangkan semangat perjuangan dan keberanian masyarakat Maluku dalam mempertahankan tanah air. Desainnya sering mencerminkan elemen-elemen yang berkaitan dengan sejarah dan budaya Maluku, menjadikannya sebagai simbol kebanggaan dan penghormatan. Batik ini sering digunakan dalam perayaan hari kemerdekaan dan acara-acara bersejarah.",
                'city' => "Ambon",
                'provinceId' => 31,
                'islandId' => 6,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Maluku/Pattimura.jpeg?t=2024-10-14T15%3A26%3A08.706Z",
            ],
            [
                'name' => "Batik Tanah Seram",
                'description' => "Batik Tanah Seram terinspirasi oleh keindahan alam dan kebudayaan pulau Seram. Motif batik ini mencerminkan kekayaan flora dan fauna serta adat istiadat masyarakat setempat. Dengan desain yang terinspirasi oleh tanah dan alam, batik ini menggambarkan hubungan yang erat antara masyarakat dan lingkungan sekitar. Batik Tanah Seram sering digunakan dalam acara adat dan tradisi untuk menunjukkan kecintaan terhadap budaya dan tanah air.",
                'city' => "Seram",
                'provinceId' => 31,
                'islandId' => 6,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Maluku/TanahSeram.jpg?t=2024-10-14T15%3A26%3A13.997Z",
            ],
            [
                'name' => "Batik Pala Salawaku",
                'description' => "Batik Pala Salawaku terinspirasi oleh rempah-rempah terkenal dari Maluku, khususnya pala. Motif ini melambangkan kekayaan alam Maluku yang diakui di seluruh dunia. Batik ini juga menceritakan sejarah perdagangan rempah yang menghubungkan Maluku dengan berbagai penjuru dunia. Dengan desain yang menggambarkan biji pala dan elemen alam lainnya, batik ini menjadi simbol identitas dan kekayaan budaya masyarakat Maluku.",
                'city' => "Ambon",
                'provinceId' => 31,
                'islandId' => 6,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Maluku/PalaSalawaku.jpeg?t=2024-10-14T15%3A26%3A21.287Z",
            ],
            [
                'name' => "Batik Tifa Totobuang",
                'description' => "Batik Tifa Totobuang mengacu pada alat musik tradisional yang digunakan dalam berbagai acara budaya di Maluku. Motif batik ini menggambarkan kesenangan dan semangat dalam merayakan kebersamaan dan tradisi. Tifa Totobuang melambangkan keterikatan masyarakat Maluku dengan seni dan budaya, serta menjadi simbol penyampaian pesan-pesan melalui irama dan nada. Batik ini sering digunakan dalam festival dan perayaan, menjadi penghubung antara generasi yang berbeda.",
                'city' => "Ambon",
                'provinceId' => 31,
                'islandId' => 6,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Maluku/Tifa%20Totobuang.jpeg?t=2024-10-14T15%3A26%3A31.408Z",
            ],
            [
                'name' => "Batik Pantai Ambon",
                'description' => "Batik Pantai Ambon terinspirasi oleh keindahan alam Pantai Ambon yang mempesona. Motifnya mencerminkan ombak, pasir, dan keanekaragaman hayati laut yang dapat ditemukan di sepanjang garis pantai. Batik ini melambangkan kedamaian dan kesejukan, dengan desain yang menunjukkan hubungan erat antara masyarakat Ambon dan laut. Warna-warna cerah dan motif yang dinamis membuat batik ini menjadi pilihan populer untuk dikenakan dalam acara santai maupun formal, sekaligus menggambarkan kebanggaan akan keindahan alam setempat. Batik Pantai Ambon sering digunakan dalam festival budaya dan perayaan sebagai simbol cinta terhadap lingkungan.",
                'city' => "Ambon",
                'provinceId' => 31,
                'islandId' => 6,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Maluku/Pantai%20Ambon.png",
            ],

            //NTT
            [
                'name' => "Batik Kuda Sepasang",
                'description' => "Batik Kuda Sepasang merupakan lambang persatuan dan cinta, terinspirasi oleh kuda yang melambangkan kekuatan dan keindahan. Motifnya seringkali menggambarkan dua ekor kuda yang berhadapan, mencerminkan hubungan harmonis dalam kehidupan masyarakat Nusa Tenggara Timur. Warna-warna cerah dan kontras dalam desainnya menunjukkan keragaman budaya yang ada di daerah ini. Batik ini biasanya digunakan dalam berbagai upacara adat, perayaan, dan juga sebagai pakaian sehari-hari.",
                'city' => "Kupang",
                'provinceId' => 19,
                'islandId' => 8,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/NTT/KudaSepasang.jpg?t=2024-10-14T15%3A33%3A19.824Z",
            ],
            [
                'name' => "Batik Liris Kupang",
                'description' => "Batik Liris Kupang adalah motif batik yang menggambarkan keindahan flora dan fauna yang ada di Kupang. Desainnya menonjolkan garis-garis halus yang membentuk pola liris, memberikan kesan elegan dan anggun. Batik ini mencerminkan kekayaan alam Nusa Tenggara Timur, serta melambangkan harapan dan semangat baru bagi masyarakat setempat. Warna yang digunakan bervariasi dari nuansa pastel hingga warna-warna cerah yang mencerminkan kehangatan daerah ini.",
                'city' => "Kupang",
                'provinceId' => 19,
                'islandId' => 8,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/NTT/LirisKupang.png?t=2024-10-14T15%3A33%3A28.692Z",
            ],
            [
                'name' => "Batik Pucuk Mekar",
                'description' => "Batik Pucuk Mekar menggambarkan motif daun dan bunga yang sedang mekar, simbol dari kehidupan dan pertumbuhan. Motif ini sering digunakan dalam perayaan dan acara penting sebagai lambang harapan dan keberkahan. Dengan perpaduan warna yang segar, batik ini mencerminkan keindahan alam Nusa Tenggara Timur. Desain yang ceria dan penuh warna ini menjadikan batik ini sebagai pilihan yang populer di kalangan masyarakat.",
                'city' => "Kupang",
                'provinceId' => 19,
                'islandId' => 8,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/NTT/PucukMekar.png?t=2024-10-14T15%3A33%3A44.443Z",
            ],
            [
                'name' => "Batik Teguh Bersatu",
                'description' => "Batik Teguh Bersatu adalah lambang dari kekuatan dan persatuan masyarakat Nusa Tenggara Timur. Motif batik ini menunjukkan pola-pola geometris yang saling terhubung, menggambarkan hubungan erat antaranggota masyarakat. Dengan warna yang kuat dan berani, batik ini merefleksikan semangat perjuangan dan kerjasama yang ada di antara mereka. Batik ini sering dipakai dalam acara-acara resmi dan pertemuan adat.",
                'city' => "Kupang",
                'provinceId' => 19,
                'islandId' => 8,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/NTT/TeguhBersatu.png?t=2024-10-14T15%3A33%3A51.924Z",
            ],
            [
                'name' => "Batik Kuda Kupang",
                'description' => "Batik Kuda Kupang terinspirasi oleh kuda-kuda yang menjadi bagian penting dari budaya lokal. Motif ini menggambarkan kuda dengan desain yang artistik dan penuh warna, melambangkan kekuatan, kebanggaan, dan kebudayaan masyarakat Nusa Tenggara Timur. Batik ini digunakan dalam berbagai acara, termasuk perayaan dan upacara adat, serta menjadi simbol identitas masyarakat Kupang.",
                'city' => "Kupang",
                'provinceId' => 19,
                'islandId' => 8,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/NTT/Kuda%20Kupang.jpg?t=2024-10-14T15%3A33%3A57.641Z",
            ],
            [
                'name' => "Batik Kupang Rukun",
                'description' => "Batik Kupang Rukun adalah simbol persatuan dan harmoni dalam masyarakat. Motifnya sering menggambarkan elemen-elemen yang saling melengkapi, mencerminkan semangat kebersamaan dan gotong royong. Dengan penggunaan warna-warna yang harmonis, batik ini menjadi pilihan yang tepat untuk digunakan dalam berbagai acara, baik formal maupun non-formal, sebagai representasi cinta dan kesatuan.",
                'city' => "Kupang",
                'provinceId' => 19,
                'islandId' => 8,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/NTT/KupangRukun.jpg?t=2024-10-14T15%3A34%3A03.744Z",
            ],

            //NTB
            [
                'name' => "Batik Daun Sirih",
                'description' => "Batik Daun Sirih merupakan salah satu motif batik yang terinspirasi dari bentuk daun sirih. Motif ini mencerminkan nilai-nilai kehidupan masyarakat yang erat dengan tradisi dan budaya. Dengan penggunaan warna yang segar dan alami, batik ini melambangkan kesegaran dan harapan. Setiap detail pada batik ini menceritakan kisah tentang ketahanan dan kebersamaan masyarakat NTB dalam menjaga budaya dan tradisi mereka. Motif ini sering digunakan dalam berbagai acara resmi dan perayaan.",
                'city' => "Mataram",
                'provinceId' => 18,
                'islandId' => 7,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/NTB/DaunSirih.jpeg?t=2024-10-14T15%3A44%3A15.426Z",
            ],
            [
                'name' => "Batik Bale Lumbu",
                'description' => "Batik Bale Lumbu adalah motif batik yang terinspirasi dari bentuk dan desain rumah tradisional suku Sasak. Motif ini menggambarkan arsitektur rumah yang khas dan mencerminkan keindahan budaya NTB. Dengan pola yang elegan dan warna yang hangat, batik ini membawa nuansa kearifan lokal. Setiap goresan dan bentuk dalam batik ini adalah simbol dari kehidupan sehari-hari masyarakat yang dekat dengan alam dan tradisi. Batik Bale Lumbu sering dikenakan pada acara adat dan perayaan penting.",
                'city' => "Bima",
                'provinceId' => 18,
                'islandId' => 7,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/NTB/BaleLumbu.png",
            ],
            [
                'name' => "Batik Tenun Bima",
                'description' => "Batik Tenun Bima menggabungkan teknik batik dengan seni tenun yang telah ada sejak lama di Bima. Motif batik ini kaya akan warna dan pola, mencerminkan keindahan alam dan budaya masyarakat Bima. Batik ini melambangkan semangat dan keteguhan masyarakat dalam mempertahankan warisan budaya. Dalam setiap seratnya, terdapat cerita yang menghubungkan generasi, menjadikan batik ini tidak hanya sekedar pakaian, tetapi juga sebuah karya seni yang hidup. Batik Tenun Bima sering dikenakan dalam acara-acara formal dan budaya.",
                'city' => "Bima",
                'provinceId' => 18,
                'islandId' => 7,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/NTB/TenunanBima.png",
            ],
            [
                'name' => "Batik Tari Persean",
                'description' => "Batik Tari Persean terinspirasi dari tarian tradisional yang terkenal di NTB, yaitu Tari Persean. Motif ini mencerminkan gerakan, semangat, dan keindahan dari tarian tersebut. Dengan pola yang dinamis dan warna yang cerah, batik ini menggambarkan keceriaan dan kekuatan budaya NTB. Setiap detail pada batik ini menggambarkan cerita dan makna dari tari tersebut, menjadikannya unik dan berharga. Batik Tari Persean sering digunakan dalam acara seni dan budaya, serta sebagai simbol kebanggaan masyarakat NTB.",
                'city' => "Mataram",
                'provinceId' => 18,
                'islandId' => 7,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/NTB/TariPersean.png?t=2024-10-14T15%3A44%3A43.563Z",
            ],

            //Bali
            [
                'name' => "Batik Merak Abyorhokokai",
                'description' => "Batik Merak Abyorhokokai adalah jenis batik khas Bali yang menggambarkan keindahan dan kemegahan burung merak. Motif ini terkenal dengan detailnya yang halus dan penggunaan warna-warna cerah yang merepresentasikan keindahan alam Bali. Dalam budaya Bali, merak sering kali melambangkan keanggunan dan kekuatan, yang tercermin dalam motif batik ini. Setiap helaian kain Batik Merak Abyorhokokai sering digunakan dalam upacara keagamaan dan kegiatan adat sebagai lambang kemuliaan. Pembuatan batik ini memerlukan ketelitian dan kecermatan tinggi, mulai dari proses menggambar motif hingga pewarnaan. Dengan desain yang elegan dan penuh makna, batik ini menjadi salah satu kebanggaan masyarakat Bali dan diminati wisatawan.",
                'city' => "Denpasar",
                'provinceId' => 17,
                'islandId' => 9,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Bali/Merak%20Abyorhokokai.jpg?t=2024-10-16T09%3A54%3A44.783Z",
            ],
            [
                'name' => "Batik Buketan",
                'description' => "Batik Buketan merupakan salah satu jenis batik yang berasal dari Bali, dengan motif bunga yang menjadi ciri khasnya. Nama \"buketan\" diambil dari kata \"bouquet\" yang berarti rangkaian bunga. Motif ini biasanya menampilkan bunga-bunga indah yang disusun sedemikian rupa sehingga menciptakan harmoni visual yang memukau. Warna-warna yang digunakan dalam Batik Buketan sering kali cerah dan menggambarkan semangat serta keceriaan masyarakat Bali. Pembuatan Batik Buketan melibatkan proses yang rumit mulai dari pembuatan pola, pencantingan, hingga pewarnaan yang memerlukan kesabaran dan keterampilan. Selain digunakan dalam kegiatan sehari-hari, Batik Buketan juga sering dipakai dalam acara-acara adat dan keagamaan. Keindahan motifnya membuat batik ini menjadi salah satu pilihan oleh-oleh khas Bali.",
                'city' => "Singaraja",
                'provinceId' => 17,
                'islandId' => 9,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Bali/Buketan.jpeg?t=2024-10-16T09%3A54%3A57.003Z",
            ],
            [
                'name' => "Batik Barong Bali",
                'description' => "Batik Barong Bali adalah batik yang mengusung tema Barong, yang merupakan simbol kekuatan pelindung dalam kepercayaan masyarakat Bali. Motif Barong ini menampilkan wujud Barong sebagai pelindung dari roh jahat, dan sering digunakan dalam upacara adat sebagai lambang perlindungan dan keselamatan. Batik ini tidak hanya sekadar kain, tetapi juga sarana untuk menyampaikan nilai-nilai kebudayaan Bali. Warna-warna yang digunakan biasanya dominan merah, hitam, dan kuning, yang memberikan kesan magis dan sakral. Pembuatan Batik Barong Bali memerlukan ketelitian tinggi, mulai dari menggambar motif hingga proses pewarnaan yang dilakukan secara hati-hati. Batik ini sering dijadikan suvenir atau oleh-oleh khas bagi wisatawan yang berkunjung ke Bali karena mengandung filosofi dan nilai budaya yang mendalam.",
                'city' => "Gianyar",
                'provinceId' => 17,
                'islandId' => 9,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Bali/Barong%20Bali.webp?t=2024-10-16T09%3A55%3A12.464Z",
            ],
            [
                'name' => "Batik Pisan Bali",
                'description' => "Batik Pisan Bali adalah salah satu batik yang menggabungkan motif pisang dengan sentuhan seni khas Bali. Motif pisang ini melambangkan kemakmuran dan keberkahan, yang sangat dihargai dalam budaya Bali. Selain itu, motif ini juga menggambarkan hubungan yang erat antara manusia dan alam. Warna-warna yang digunakan pada Batik Pisan Bali biasanya natural dan terinspirasi dari alam, seperti hijau daun, coklat tanah, dan biru laut. Proses pembuatannya memerlukan ketelitian, terutama pada saat mencanting pola pisang yang menjadi ciri khasnya. Batik ini sering digunakan dalam kegiatan sehari-hari maupun upacara adat, serta menjadi pilihan favorit sebagai oleh-oleh bagi para wisatawan yang ingin membawa pulang sedikit keindahan Bali. Keunikannya menjadikan Batik Pisan Bali sebagai salah satu kekayaan budaya yang dilestarikan di pulau ini.",
                'city' => "Tabanan",
                'provinceId' => 17,
                'islandId' => 9,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Bali/Pisan.png?t=2024-10-16T09%3A55%3A29.633Z",
            ],
            [
                'name' => "Batik Ulamsari",
                'description' => "Batik Ulamsari merupakan batik khas Bali yang menampilkan motif-motif flora dan fauna laut, seperti ikan, terumbu karang, dan bunga-bunga laut. Motif ini terinspirasi dari keindahan alam bawah laut Bali yang terkenal di seluruh dunia. Warna-warna yang digunakan pada Batik Ulamsari biasanya cerah, menggambarkan keindahan dan keragaman kehidupan laut. Setiap motif yang digoreskan di atas kain mencerminkan hubungan yang erat antara masyarakat Bali dengan laut sebagai sumber kehidupan dan inspirasi. Pembuatan Batik Ulamsari melalui berbagai tahapan yang membutuhkan keahlian khusus, mulai dari menggambar pola hingga proses pewarnaan yang dilakukan secara manual. Batik ini menjadi salah satu produk unggulan yang banyak dicari oleh para pecinta seni dan budaya Bali, serta menjadi suvenir favorit bagi para wisatawan.",
                'city' => "Denpasar",
                'provinceId' => 17,
                'islandId' => 9,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Bali/Ulamsari.jpg?t=2024-10-16T09%3A55%3A45.907Z",
            ],
            [
                'name' => "Batik Penari Bali",
                'description' => "Batik Penari Bali adalah batik dengan motif yang menggambarkan keindahan gerakan tari-tarian Bali. Motif ini sering menampilkan sosok penari dengan kostum tradisional Bali yang penuh detail. Tarian dalam motif ini melambangkan keanggunan, keseimbangan, dan harmoni antara manusia dan alam. Warna yang digunakan pada Batik Penari Bali sering kali cerah dan dinamis, mencerminkan energi yang ada dalam setiap gerakan tarian Bali. Proses pembuatan batik ini membutuhkan ketelitian tinggi, terutama dalam menggambarkan detail-detail motif penari yang khas. Batik Penari Bali sering digunakan dalam acara-acara adat dan keagamaan, serta menjadi salah satu daya tarik bagi wisatawan yang ingin membawa pulang kain khas Bali yang kaya akan nilai seni dan budaya.",
                'city' => "Ubud",
                'provinceId' => 17,
                'islandId' => 9,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Bali/PenariBali.webp?t=2024-10-16T09%3A55%3A54.659Z",
            ],
            [
                'name' => "Batik Singa Barong",
                'description' => "Batik Singa Barong adalah jenis batik Bali yang menampilkan motif singa sebagai simbol kekuatan dan keberanian. Dalam budaya Bali, singa sering kali dianggap sebagai penjaga dan pelindung, yang digambarkan dengan megah dalam motif batik ini. Warna-warna yang digunakan pada Batik Singa Barong biasanya kaya dan kontras, seperti merah, emas, dan hitam, yang memberikan kesan kekuatan dan wibawa. Batik ini sering digunakan dalam upacara adat dan kegiatan budaya sebagai simbol perlindungan dan keberanian. Pembuatan Batik Singa Barong memerlukan keahlian tinggi dalam mencanting dan mewarnai, sehingga menghasilkan motif yang detail dan indah. Batik ini menjadi salah satu pilihan oleh-oleh khas bagi wisatawan yang ingin mengenal lebih dalam tentang kebudayaan Bali dan nilai-nilai yang dijunjung tinggi oleh masyarakatnya.",
                'city' => "Klungkung",
                'provinceId' => 17,
                'islandId' => 9,
                'linkImage' => "https://jjittozptnoaoseyrvcz.supabase.co/storage/v1/object/public/hology/Batik/Bali/Singa%20Barong.jpg?t=2024-10-16T09%3A56%3A03.536Z",
            ],
        ];
    }
}
